sepak_bola_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('tiket/', include('tiket.urls')),
    path('pertandingan/', include('pertandingan.urls')),
    path('rapat/', include('rapat.urls')),
    path('peminjaman_stadium/', include('peminjaman_stadium.urls')),
    path('team/', include('team.urls')),
]

team/urls.py
from django.urls import path
from team.views import get_team, reg_pelatih, reg_pemain, team, set_captain, delete_player, delete_coach, insert_pelatih, insert_pemain, register_team

app_name = 'team'

urlpatterns = [
    path('', team, name='team'),
    path('get_team', get_team, name='get_team'),
    path('pelatih', reg_pelatih, name='reg_pelatih'),
    path('pemain', reg_pemain, name='reg_pemain'),
    path('set_captain/<uuid:player_id>/', set_captain, name='set_captain'),
    path('delete_player/<uuid:player_id>/', delete_player, name='delete_player'),
    path('delete_coach/<uuid:pelatih_id>/', delete_coach, name='delete_coach'),
    path('insert_pelatih', insert_pelatih, name='insert_pelatih'),
    path('insert_pemain/', insert_pemain, name='insert_pemain'),
    path('register_team', register_team, name='register_team' )
]

team/models.py
from django.db import models

# Create your models here.

team/views.py
from django.shortcuts import render, redirect
from utils.query import query
from django.db import connection
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.db import IntegrityError
from django.contrib import messages

# Create your views here

# @login_required
def team(request):
    with connection.cursor() as cursor:
        cursor.execute("SET SEARCH_PATH TO 'u-league'")
        # Get the manager's team information from the database
        cursor.execute("""
            SELECT tm.nama_tim
            FROM tim_manajer tm
            INNER JOIN manajer m ON tm.id_manajer = m.id_manajer
            WHERE m.username = %s
        """, [request.session["username"]])
        team_info = cursor.fetchone()

    if team_info is not None and team_info[0]:
        return get_team(request)
    else:
        return render(request, 'pendaftaran-tim.html')
    
def register_team(request):
    if request.method == 'POST':
        nama_tim = request.POST.get('name')
        universitas = request.POST.get('univ')

        username = request.session["username"]
        manager_id_result = query(f"SELECT m.id_manajer FROM manajer m WHERE m.Username = '{username}'")
        manager_id = manager_id_result[0].id_manajer

        with connection.cursor() as cursor:
            # Check if the manager already has a team
            cursor.execute("""
                SELECT COUNT(*) FROM tim_manajer tm
                INNER JOIN manajer m ON tm.id_manajer = m.id_manajer
                WHERE m.username = %s
            """, [username])
            team_count = cursor.fetchone()[0]

            if team_count > 0:
                return redirect('team:get_team')
            else:
                # Create a new team for the manager
                cursor.execute("""
                    INSERT INTO tim (nama_tim, universitas)
                    VALUES (%s, %s)
                """, [nama_tim, universitas])

                cursor.execute("""
                    INSERT INTO tim_manajer (id_manajer, nama_tim)
                    VALUES (%s, %s)
                """, [manager_id, nama_tim])

        return redirect('team:get_team')

    return render(request, 'pendaftaran-tim.html')

def get_team(request):
    username = request.session["username"]
    nama_tim_result = query(f"SELECT tm.Nama_Tim FROM Tim_Manajer tm JOIN manajer m ON tm.ID_Manajer = m.ID_Manajer WHERE m.Username = '{username}'")
    nama_tim = nama_tim_result[0].nama_tim
    with connection.cursor() as cursor:
        cursor.execute("SET SEARCH_PATH TO 'u-league'")
        cursor.execute("""
            SELECT pemain.id_pemain,  CONCAT(pemain.nama_depan, ' ', pemain.nama_belakang) AS Nama_Pemain, pemain.nomor_hp, pemain.tgl_lahir, pemain.is_captain,
            pemain.posisi, pemain.npm, pemain.jenjang
            FROM pemain
            WHERE nama_tim = %s
        """, [nama_tim])
        pemain_raw = cursor.fetchall()

        pemain_list = []

        for res in pemain_raw:
            pemain_list.append({
                "id": res[0],
                "nama_pemain": res[1],
                "nomor_hp": res[2],
                "tgl_lahir": res[3],
                "is_captain": res[4],
                "posisi": res[5],
                "npm": res[6],
                "jenjang": res[7],
            })

        cursor.execute(f"""
    SELECT pelatih.id_pelatih, CONCAT(Non_Pemain.Nama_Depan, ' ', Non_Pemain.Nama_Belakang) AS Nama, Non_Pemain.Nomor_HP, Non_Pemain.Email, Non_Pemain.Alamat, Spesialisasi_Pelatih.Spesialisasi, Pelatih.Nama_Tim
FROM Pelatih
JOIN Non_Pemain ON Pelatih.ID_Pelatih = Non_Pemain.ID
JOIN Spesialisasi_Pelatih ON Pelatih.ID_Pelatih = Spesialisasi_Pelatih.ID_Pelatih
WHERE nama_tim='{nama_tim}'
    """)
        pelatih_raw = cursor.fetchall()

        pelatih_list = []

        for res in pelatih_raw:
            pelatih_list.append(
            
                {
                    "id": res[0],
                    "nama_pelatih": res[1],
                    "nomor_hp": res[2],
                    "email": res[3],
                    "alamat": res[4],
                    "spesialisasi": res[5],
        
                }
            )

        # ris = cursor.fetchall()
        print(nama_tim)

        context = {
            "pelatih_list": pelatih_list,
            "pemain_list": pemain_list,
        }

        return render(request, "tim.html", context)

def reg_pemain(request):
    with connection.cursor() as cursor:
        cursor.execute("SET SEARCH_PATH TO 'u-league'")
        cursor.execute("""
            SELECT CONCAT(nama_depan, ' ', nama_belakang) AS Nama_Pemain
            FROM pemain
            WHERE nama_tim IS NULL
        """)
        pemain_names = [res[0] for res in cursor.fetchall()]

    context = {
        "pemain_names": pemain_names
    }

    return render(request, "pemain.html", context)

def reg_pelatih(request):
    error_message = request.GET.get('error_message')  # Get the error_message query parameter

    with connection.cursor() as cursor:
        cursor.execute("SET SEARCH_PATH TO 'u-league'")
        cursor.execute("""
            SELECT CONCAT(Non_Pemain.Nama_Depan, ' ', Non_Pemain.Nama_Belakang) AS Nama, Spesialisasi_Pelatih.Spesialisasi
            FROM Pelatih
            JOIN Non_Pemain ON Pelatih.ID_Pelatih = Non_Pemain.ID
            JOIN Spesialisasi_Pelatih ON Pelatih.ID_Pelatih = Spesialisasi_Pelatih.ID_Pelatih
            WHERE Pelatih.Nama_Tim IS NULL
        """)
        pelatih_options = [
            {
                'nama_pelatih': res[0],
                'spesialisasi': res[1]
            } for res in cursor.fetchall()
        ]

    context = {
        'pelatih_options': pelatih_options,
        'error_message': error_message  # Pass the error message to the template context
    }

    return render(request, 'pelatih.html', context)

def insert_pemain(request):
    username = request.session["username"]
    nama_tim_result = query(f"SELECT tm.Nama_Tim FROM Tim_Manajer tm JOIN manajer m ON tm.ID_Manajer = m.ID_Manajer WHERE m.Username = '{username}'")
    nama_tim = nama_tim_result[0].nama_tim

    if request.method == 'POST':
        selected_pemain_nama = request.POST.get('pemain')

        with connection.cursor() as cursor:
            cursor.execute("SET SEARCH_PATH TO 'u-league'")

            # Get the selected pemain information from the database
            cursor.execute("""
                SELECT Pemain.ID_Pemain
                FROM Pemain
                WHERE CONCAT(pemain.nama_depan, ' ', pemain.nama_belakang) = %s
                    AND Pemain.Nama_Tim IS NULL
            """, [selected_pemain_nama])

            pemain_info = cursor.fetchone()

            if pemain_info:
                pemain_id = pemain_info[0]

                cursor.execute(f"UPDATE Pemain SET Nama_Tim='{nama_tim}' WHERE ID_Pemain = '{pemain_id}'")
                print("Pemain inserted into the team")

    return redirect('team:get_team')

from django.db import IntegrityError

from django.db import IntegrityError


from django.shortcuts import redirect

from django.urls import reverse
from django.shortcuts import redirect

def insert_pelatih(request):
    error_message = None  # Initialize the error message variable
    username = request.session["username"]
    nama_tim_result = query(f"SELECT tm.Nama_Tim FROM Tim_Manajer tm JOIN manajer m ON tm.ID_Manajer = m.ID_Manajer WHERE m.Username = '{username}'")
    nama_tim = nama_tim_result[0].nama_tim

    if request.method == 'POST':
        selected_pelatih_nama = request.POST['pelatih']

        with connection.cursor() as cursor:
            
                cursor.execute("SET SEARCH_PATH TO 'u-league'")

                # Get the selected pelatih information from the database
                cursor.execute("""
                    SELECT Pelatih.ID_Pelatih, Spesialisasi
                    FROM Pelatih
                    JOIN Non_Pemain ON Pelatih.ID_Pelatih = Non_Pemain.ID
                    JOIN Spesialisasi_Pelatih ON Pelatih.ID_Pelatih = Spesialisasi_Pelatih.ID_Pelatih
                    WHERE CONCAT(Non_Pemain.Nama_Depan, ' ', Non_Pemain.Nama_Belakang) = %s
                        AND Pelatih.Nama_Tim IS NULL
                """, [selected_pelatih_nama])

                pelatih_info = cursor.fetchone()

                if pelatih_info:
                    pelatih_id, spesialisasi = pelatih_info

                    try:
                        cursor.execute(f"UPDATE Pelatih SET Nama_Tim='{nama_tim}' WHERE id_pelatih = '{pelatih_id}'")
                        print("Pelatih inserted into the team")
                    except Exception as e:
                        if "The coach already has the same specialization." in str(e):
                            error_message = "An error occurred: The coach already has the same specialization."
                        elif "The team already has two coaches." in str(e):
                            error_message = "An error occurred: The team already has two coaches."
                        else:
                            error_message = "An error occurred while updating the coach."
                        return redirect(reverse('team:reg_pelatih') + f'?error_message={error_message}')
                else:
                    error_message = "Selected coach is not available or already assigned to a team."

    return redirect('team:get_team')


def set_captain(request, player_id):
    with connection.cursor() as cursor:
        cursor.execute("SET SEARCH_PATH TO 'u-league'")

        cursor.execute(f"UPDATE Pemain SET is_captain = true WHERE id_pemain = '{player_id}'")

        # Print a message to check if the update query was executed
        print("Player captain updated:", cursor.rowcount)

    return redirect('team:get_team')

def delete_player(request, player_id):
    with connection.cursor() as cursor:

team/templates/pelatih.html
{% extends 'manajerBase.html' %}
{% load static %}

{% block meta %}
	<title>Pelatih</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
	<style>
body {
	background-color: #6c0000;
	font-family: Arial, sans-serif;
	margin: 0;
	padding: 0;
}

.container {
	max-width: 1200px;
	margin: 0 auto;
	padding: 50px;
	display: flex;
	flex-wrap: wrap;
	justify-content: center;
	align-items: center;
}

.box {
    width: 900px; 
    height: 400px; 
	background-color: #fff;
	box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
	border-radius: 20px;
	padding: 20px;
	margin: 20px;
	min-width: center; 
    
}

.box h2 {
	font-weight: bold; 
	margin-top: 20;
    font-size: 30px;
}

.box h3 {
	margin-top: 0;
	margin-bottom: 0;
    font-size: 20px;
}
.box p{
    margin-top: 0;
	margin-bottom: 0;
    font-size: 15px;
    font-weight: lighter;
}
.box2 {
    width: 250px; 
    height: 300px; 
	background-color: #6c0000;
	box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
	border-radius: 20px;
	padding: 20px;
	margin: 20px;
	min-width: center; 
    position: relative;
    top: -40px;
    left: -30px;
    
}
.submit-button {
    background-color: #6c0000; /* Green */
    border: none;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
    border-radius: 10px;
    font-size: 20px;
    font-weight: bold;
  }
  .my-select {
  width: 800px; /* set the desired width */
  height: 40px; /* set the desired height */
  font-size: 20;
  margin-bottom: 30px;
}
.dropdown-container {
  display: flex;
  justify-content: center;
  align-items: center;
}

	</style>
{% endblock meta %}
  <!-- Place this code where you want the error message to be displayed -->

  {% block content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
	<!-- Place this code where you want the error message to be displayed -->
<!-- Place this code where you want the error message to be displayed -->
{% if error_message %}
    <div class="alert alert-danger" role="alert">
        {{ error_message }}
    </div>
{% endif %}
    <div class="container">
		<div class="box">
			<h2 style="margin-bottom: 50px">DAFTAR PELATIH</h2>
            <style>
                h2{
                    text-align: center;
                }
            </style>
<label for="name" style="display: block; margin: 0 auto; font-weight: bold; font-size: 20px; text-align: center; margin-bottom: 10px;">Pelatih yang Mau Didaftarkan</label>
<div class="dropdown-container">
    <form action="{% url 'team:insert_pelatih' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="pelatih">Pelatih:</label>
            <select class="my-select" name="pelatih">
                {% for pelatih_option in pelatih_options %}
                <option value="{{ pelatih_option.nama_pelatih }}">{{ pelatih_option.nama_pelatih }} - {{ pelatih_option.spesialisasi }}</option>
                {% endfor %}
            </select>
        </div>
        <div style="display: flex; justify-content: center;">
            <input type="submit" value="Submit" class="submit-button">
        </div>
    </form>
</div>
{% endblock content %}

team/templates/pemain.html
{% extends 'manajerBase.html' %}
{% load static %}

{% block meta %}
	<title>Pemain</title>
    <title>Pendaftaran Tim</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
	<style>
body {
	background-color: #6c0000;
	font-family: Arial, sans-serif;
	margin: 0;
	padding: 0;
}

.container {
	max-width: 1200px;
	margin: 0 auto;
	padding: 50px;
	display: flex;
	flex-wrap: wrap;
	justify-content: center;
	align-items: center;
}

.box {
    width: 900px; 
    height: 400px; 
	background-color: #fff;
	box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
	border-radius: 20px;
	padding: 20px;
	margin: 20px;
	min-width: center; 
    
}

.box h2 {
	font-weight: bold; 
	margin-top: 20;
    font-size: 30px;
}

.box h3 {
	margin-top: 0;
	margin-bottom: 0;
    font-size: 20px;
}
.box p{
    margin-top: 0;
	margin-bottom: 0;
    font-size: 15px;
    font-weight: lighter;
}
.box2 {
    width: 250px; 
    height: 300px; 
	background-color: #6c0000;
	box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
	border-radius: 20px;
	padding: 20px;
	margin: 20px;
	min-width: center; 
    position: relative;
    top: -40px;
    left: -30px;
    
}
.submit-button {
    background-color: #6c0000; /* Green */
    border: none;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
    border-radius: 10px;
    font-size: 20px;
    font-weight: bold;
  }
  .my-select {
  width: 800px; /* set the desired width */
  height: 40px; /* set the desired height */
  font-size: 20;
  margin-bottom: 30px;
}
.dropdown-container {
  display: flex;
  justify-content: center;
  align-items: center;
}

	</style>

{% endblock meta %}

{% block content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
	<div class="container">
		<div class="box">
			<h2 style="margin-bottom: 50px">DAFTAR PEMAIN</h2>
            <style>
                h2{
                    text-align: center;
                }
            </style>
        <label for="name" style="display: block; margin: 0 auto; font-weight: bold; font-size: 20px; text-align: center; margin-bottom: 10px;">Pemain yang Mau Didaftarkan</label>
        <div class ="dropdown-container">
          <form method="POST" action="{% url 'team:insert_pemain' %}">
            {% csrf_token %}
          
            <div class="form-group">
              <label for="pemain">Select a Player:</label>
              <select name="pemain" id="pemain" class="form-control">
                {% for pemain_name in pemain_names %}
                <option value="{{ pemain_name }}">{{ pemain_name }}</option>
                {% endfor %}
              </select>
            </div>
          
            <div style="display: flex; justify-content: center;">
              <input type="submit" value="Insert Player" class="submit-button">
            </div>
          </form>          
        </div>
        
{% endblock content %}

team/templates/pendaftaran-tim.html
{% extends 'manajerBase.html' %}
{% load static %}

{% block meta %}
	<title>Pendaftaran Tim</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
<style>
body {
	background-color: #6c0000;
	font-family: Arial, sans-serif;
	margin: 0;
	padding: 0;
}

.container {
	max-width: 1200px;
	margin: 0 auto;
	padding: 50px;
	display: flex;
	flex-wrap: wrap;
	justify-content: center;
	align-items: center;
}

.box {
    width: 900px; 
    height: 400px; 
	background-color: #fff;
	box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
	border-radius: 20px;
	padding: 20px;
	margin: 20px;
	min-width: center; 
    
}

.box h2 {
	font-weight: bold; 
	margin-top: 20;
    font-size: 30px;
}

.box h3 {
	margin-top: 0;
	margin-bottom: 0;
    font-size: 20px;
}
.box p{
    margin-top: 0;
	margin-bottom: 0;
    font-size: 15px;
    font-weight: lighter;
}
.box2 {
    width: 250px; 
    height: 300px; 
	background-color: #6c0000;
	box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
	border-radius: 20px;
	padding: 20px;
	margin: 20px;
	min-width: center; 
    position: relative;
    top: -40px;
    left: -30px;
    
}
.submit-button {
    background-color: #6c0000; /* Green */
    border: none;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
    border-radius: 10px;
    font-size: 20px;
    font-weight: bold;
  }
	</style>
{% endblock meta %}
{% block content %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
	<div class="container">
		<div class="box">
			<h2 style="margin-bottom: 50px">FORM REGISTRASI</h2>
            <style>
                h2{
                    text-align: center;
                }
            </style>
      <!-- t" id="name" name="name" style="display: block; margin: 0 auto; font-weight: lighter; font-size: 20px; width: 700px;margin-bottom: 30px;"> -->
      <form action="{% url 'team:register_team' %}" method="POST">
        {% csrf_token %}
        <h2 style="margin-bottom: 50px">FORM REGISTRASI</h2>
        <style>
          h2 {
            text-align: center;
          }
        </style>
        <label for="name" style="display: block; margin: 0 auto; font-weight: bold; font-size: 20px; text-align: center; margin-bottom: 10px;">Nama Tim</label>
        <input type="text" id="name" name="name" style="display: block; margin: 0 auto; font-weight: lighter; font-size: 20px; width: 700px; margin-bottom: 30px;">
        <label for="univ" style="display: block; margin: 0 auto; font-weight: bold; font-size: 20px; text-align: center; margin-bottom: 10px;">Nama Universitas</label>
        <input type="text" id="univ" name="univ" style="display: block; margin: 0 auto; font-weight: lighter; font-size: 20px; width: 700px; margin-bottom: 30px;">
        <div style="display: flex; justify-content: center;">
          <button type="submit" class="submit-button">Submit</button>
        </div>
      </form>
      
        
        </div>

{% endblock content %}

team/templates/tim.html
{% extends 'manajerBase.html' %}
{% load static %}

{% block meta %}
	<title>Tim</title>
  <title>Pendaftaran Tim</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
	<style>
body {
	background-color: #6c0000;
	font-family: Arial, sans-serif;
	margin: 0;
	padding: 0;
}

.container {
	max-width: 1200px;
	margin: 0 auto;
	padding: 50px;
	display: flex;
	flex-wrap: wrap;
	justify-content: center;
	align-items: center;
}

.box {
    width: 900px; 
    height: 700px; 
	background-color: #fff;
	box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
	border-radius: 20px;
	padding: 20px;
	margin: 20px;
	min-width: center; 
    
}

.box h2 {
	font-weight: bold; 
	margin-top: 20;
    font-size: 30px;
}

.box h3 {
	margin-top: 0;
	margin-bottom: 0;
    font-size: 20px;
}
.box p{
    margin-top: 0;
	margin-bottom: 0;
    font-size: 15px;
    font-weight: lighter;
}
.box2 {
    width: 250px; 
    height: 300px; 
	background-color: #6c0000;
	box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);
	border-radius: 20px;
	padding: 20px;
	margin: 20px;
	min-width: center; 
    position: relative;
    top: -40px;
    left: -30px;
    
}
.submit-button {
    background-color: #6c0000; /* Green */
    border: none;
    color: white;
    padding: 15px 32px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
    cursor: pointer;
    border-radius: 10px;
    font-size: 20px;
    font-weight: bold;
  }
  table {
    border-collapse: collapse;
    width: 100%;
  }

  th, td {
    text-align: left;
    padding: 8px;
  }

  th {
    background-color: #dddddd;
    border: 1px solid #dddddd;
  }

  tr:nth-child(even) {
    background-color: #f2f2f2;
  }

  td {
    border: 1px solid #dddddd;
  }
	</style>
{% endblock meta %}

{% block content %}
  <div class="container">
    <div class="box">
      <h2 style="margin-bottom: 10px">TIM</h2>
      <table>
        <thead>
          <tr>
            <th colspan="8" style="text-align: center; border-bottom: 1px solid #dddddd; border-top: 1px solid #dddddd; border-left: 1px solid #dddddd; border-right: 1px solid #dddddd;">PEMAIN</th>
          </tr>
          <tr>
            <th>Nama Pemain</th>
            <th>No HP</th>
            <th>Tanggal Lahir</th>
            <th>Is Captain</th>
            <th>Posisi</th>
            <th>NPM</th>
            <th>Jenjang</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          {% for pemain in pemain_list %}
              <tr>
                  <td>{{ pemain.nama_pemain }}</td>
                  <td>{{ pemain.nomor_hp }}</td>
                  <td>{{ pemain.tgl_lahir }}</td>
                  <td>{{ pemain.is_captain }}</td>
                  <td>{{ pemain.posisi }}</td>
                  <td>{{ pemain.npm }}</td>
                  <td>{{ pemain.jenjang }}</td>
                  <td style="text-decoration: underline;">
                      {% if not pemain.is_captain %}
                          <a href="{% url 'team:set_captain' pemain.id %}">Make Captain</a>
                      {% endif %}
                      <a href="{% url 'team:delete_player' pemain.id %}">Remove from Team</a>
                  </td>
              </tr>
          {% endfor %}
      </tbody>
      
      </table>
      <table>
        <thead>
          <tr>
            <th colspan="8" style="text-align: center; border-bottom: 1px solid #dddddd; border-top: 1px solid #dddddd; border-left: 1px solid #dddddd; border-right: 1px solid #dddddd;">PELATIH</th>
          </tr>
          <tr>
            <th>Nama Pelatih</th>
            <th>No HP</th>
            <th>Email</th>
            <th>Alamat</th>
            <th>Spesialisasi</th>
          
            <th>Action</th>
            
          </tr>
        </thead>
        <tbody>
          {% for pelatih in pelatih_list %}
            <tr>
              <td>{{ pelatih.nama_pelatih }}</td>
              <td>{{ pelatih.nomor_hp }}</td>
              <td>{{ pelatih.email }}</td>
              <td>{{ pelatih.alamat }}</td>
              <td>{{ pelatih.spesialisasi }}</td>
        
              <td style="text-decoration: underline;">
                <a href="{% url 'team:delete_coach' pelatih.id %}">Delete Coach</a>
              </td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
              
      <div style="display: flex; justify-content: center; margin-top: 30px;">
        <form action="pemain.html">
          <a href="{% url 'team:reg_pemain' %}" class="submit-button">Pemain</a>
        </form>
        <form action="pelatih.html">
          <a href="{% url 'team:reg_pelatih' %}" class="submit-button">Pelatih</a>
        </form>
      </div>
    </div>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
{% endblock content %}